packages:
  - api
  - app
  - cli
  - landing
  - mobile
  - ui

catalog:
  "@types/node": 25.3.5
  "@types/react": 19.2.14
  "@types/react-dom": 19.2.3
  commander: 14.0.3
  react: 19.2.4
  react-dom: 19.2.4
  react-native: 0.84.1
  tailwindcss: 4.2.1
  typescript: 5.9.3
  zod: 3.25.76
