packages:
  - api
  - app
  - charts
  - cli
  - docs
  - landing
  - mobile
  - design-tokens
catalog:
  "@types/node": 25.6.0
  "@types/react": 19.2.14
  "@types/react-dom": 19.2.3
  commander: 14.0.3
  react: 19.2.4
  react-dom: 19.2.4
  react-native: 0.84.1
  tailwindcss: 4.2.4
  typescript: 5.9.3
  zod: 3.25.76
  lodash: 4.18.1
  "@types/lodash": 4.17.24
  "@lingual/i18n-check": 0.9.4
overrides:
  cli@<1.0.0: ">=1.0.0"
  lodash@>=4.0.0 <=4.17.22: ">=4.17.23"
  minimatch@>=9.0.0 <9.0.6: ">=9.0.6"
  minimatch@>=9.0.0 <9.0.7: ">=9.0.7"
  serialize-javascript@<=7.0.2: ">=7.0.3"
  tar@<=7.5.9: ">=7.5.10"
  svgo@=4.0.0: ">=4.0.1"
