name: Lint

on:
  pull_request:
  push:
    branches:
      - dev
      - test
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        uses: ./.github/actions/install-deps
        with:
          setup-node: "true"
          frozen-lockfile: "true"

      - name: Check dependency licenses
        uses: ukorvl/custom-github-actions/check-npm-licenses@3c31000846c9d3457f3ef8707fd2ec652a1e79db
        with:
          ROOT_DIR: .
          PACKAGE_PATHS: |
            .
            api
            app
            cli
            landing
            mobile
            ui

      - name: Run lint checks
        uses: ./.github/actions/lint
        with:
          include-syncpack: "true"
          include-knip: "false"
