name: Label Pull Requests

on:
  - pull_request_target

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  label-pr:
    runs-on: ubuntu-slim
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          fetch-depth: 1
          persist-credentials: false
      - name: Add Labels for PR
        if: >-
          ${{
            !((github.event.pull_request.head.ref == 'main' &&
            (github.event.pull_request.base.ref == 'test' ||
            github.event.pull_request.base.ref == 'dev')) ||
            (github.event.pull_request.head.ref == 'test' &&
            github.event.pull_request.base.ref == 'dev'))
          }}
        uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213 # v6
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
          configuration-path: ".github/labeler.yaml"
